language: node_js
cache: yarn
node_js:
  - node
script:
  - npm run flow
  - npm run test
  - npm run build
  - npm run lint
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip_cleanup: true
  on:
    branch: master
